### ISSUE TITLE
Trees after world changes retain a sapling block at the bottom until looked at

### ISSUE THREAD

**Issue by Cervator** [Terasology/GrowingFlora#2]
Some sort of quantum botany going on - when observed the bottom sapling block collapses into a trunk block of the proper type :-)

![terasology-140922222835-1152x700](https://cloud.githubusercontent.com/assets/1063833/4366953/f83a797a-42c9-11e4-8046-84190d46c2c3.png)

(I figure GrowingFlora is the most apt tracker for this)

**Comment by jdrueckert** [comment]
This has been fixed.
